VALID_CATEGORY_PATHS = [
    ('video-games', 'atari', 'atari-games'),
    ('video-games', 'atari', 'atari-accessories'),
    ('video-games', 'atari', 'atari-consoles'),
    ('video-games', 'nes', 'nes-games'),
    ('video-games', 'nes', 'nes-accessories'),
    ('video-games', 'nes', 'nes-consoles'),
    ('video-games', 'snes', 'snes-games'),
    ('video-games', 'snes', 'snes-accessories'),
    ('video-games', 'snes', 'snes-consoles'),
    ('video-games', 'n64', 'n64-games'),
    ('video-games', 'n64', 'n64-accessories'),
    ('video-games', 'n64', 'n64-consoles'),
    ('video-games', 'gamecube', 'gamecube-games'),
    ('video-games', 'gamecube', 'gamecube-accessories'),
    ('video-games', 'gamecube', 'gamecube-consoles'),
    ('video-games', 'genesis', 'genesis-games'),
    ('video-games', 'genesis', 'genesis-accessories'),
    ('video-games', 'genesis', 'genesis-consoles'),
    ('video-games', 'saturn', 'saturn-games'),
    ('video-games', 'saturn', 'saturn-accessories'),
    ('video-games', 'saturn', 'saturn-consoles'),
    ('video-games', 'playstation', 'playstation-games'),
    ('video-games', 'playstation', 'playstation-accessories'),
    ('video-games', 'playstation', 'playstation-consoles'),
    ('video-games', 'ps2', 'ps2-games'),
    ('video-games', 'ps2', 'ps2-accessories'),
    ('video-games', 'ps2', 'ps2-consoles'),
    ('video-games', 'ps3', 'ps3-games'),
    ('video-games', 'ps3', 'ps3-accessories'),
    ('video-games', 'ps3', 'ps3-consoles'),
    ('video-games', 'xbox', 'xbox-games'),
    ('video-games', 'xbox', 'xbox-accessories'),
    ('video-games', 'xbox', 'xbox-consoles'),
    ('video-games', 'xbox-360', 'xbox360-games'),
    ('video-games', 'xbox-360', 'xbox360-accessories'),
    ('video-games', 'xbox-360', 'xbox360-consoles'),
    ('video-games', 'handhelds', 'handhelds-games'),
    ('video-games', 'handhelds', 'handhelds-accessories'),
    ('video-games', 'handhelds', 'handhelds-consoles'),
    ('clothing', 'vintage', 'tops'),
    ('clothing', 'vintage', 'pants'),
    ('clothing', 'vintage', 'skirts'),
    ('clothing', 'vintage', 'dresses'),
    ('clothing', 'vintage', 'outerwear'),
    ('clothing', 'vintage', 'band-tees'),
    ('clothing', 'vintage', 'jumpsuits'),
    ('clothing', 'vintage', 'shoes', 'sneakers'),
    ('clothing', 'vintage', 'shoes', 'boots'),
    ('clothing', 'vintage', 'shoes', 'sandals'),
    ('clothing', 'vintage', 'shoes', 'dress'),
    ('clothing', 'vintage', 'accessories'),
    ('clothing', 'modern', 'tops'),
    ('clothing', 'modern', 'pants'),
    ('clothing', 'modern', 'skirts'),
    ('clothing', 'modern', 'dresses'),
    ('clothing', 'modern', 'outerwear'),
    ('clothing', 'modern', 'athleisure'),
    ('clothing', 'modern', 'jumpsuits'),
    ('clothing', 'modern', 'shoes', 'sneakers'),
    ('clothing', 'modern', 'shoes', 'boots'),
    ('clothing', 'modern', 'shoes', 'sandals'),
    ('clothing', 'modern', 'shoes', 'dress'),
    ('clothing', 'modern', 'accessories'),
    ('clothing', 'band-tees'),
    ('clothing', 'sweaters'),
    ('clothing', 'hoodies'),
    ('clothing', 'jumpsuits'),
    ('clothing', 'boho'),
    ('clothing', 'designer'),
    ('clothing', 'shoes', 'sneakers'),
    ('clothing', 'shoes', 'boots'),
    ('clothing', 'shoes', 'sandals'),
    ('clothing', 'shoes', 'dress'),
    ('clothing', 'accessories', 'umbrellas'),
    ('clothing', 'accessories', 'bags'),
    ('clothing', 'accessories', 'hats'),
    ('clothing', 'accessories', 'belts'),
    ('clothing', 'accessories', 'jewelry'),
    ('clothing', 'accessories', 'other'),
    ('clothing', 'kids', 'tops'),
    ('clothing', 'kids', 'bottoms'),
    ('clothing', 'kids', 'dresses'),
    ('clothing', 'kids', 'outerwear'),
    ('clothing', 'kids', 'shoes'),
    ('clothing', 'kids', 'accessories'),
    ('collectibles', 'trading-cards', 'pokemon'),
    ('collectibles', 'trading-cards', 'magic'),
    ('collectibles', 'trading-cards', 'yugioh'),
    ('collectibles', 'trading-cards', 'sports-cards'),
    ('collectibles', 'trading-cards', 'other-cards'),
    ('collectibles', 'comics', 'marvel'),
    ('collectibles', 'comics', 'dc'),
    ('collectibles', 'comics', 'indie'),
    ('collectibles', 'designer', 'accessories'),
    ('collectibles', 'toys', 'action-figures'),
    ('collectibles', 'toys', 'plushies'),
    ('collectibles', 'toys', 'vintage'),
    ('collectibles', 'pins', 'buttons'),
    ('collectibles', 'vinyl', '78s'),
    ('media', 'vinyl'),
    ('media', 'books'),
    ('media', 'cassettes'),
    ('media', 'cds'),
    ('media', 'vhs'),
    ('',),
]
